---
- import_tasks: drain.yml
  tags:
    - drain

- name: Launch API container
  community.general.docker_container:
    name: "{{ api_name }}"
    image: "{{ api_image }}"
    container_default_behavior: no_defaults
    state: started
    pull: yes
    recreate: yes
    restart_policy: always
    labels:
      json_logger: "True"
    ports:
      - "{{ api_port }}:{{ api_port }}"
    env:
      PORT: "{{ api_port | string }}"

- import_tasks: enable.yml
  tags:
    - drain
